// <auto-generated />
namespace MvcEasyOrderSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mobile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mobile));
        
        string IMigrationMetadata.Id
        {
            get { return "201211190202169_mobile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
