// <auto-generated />
namespace MvcEasyOrderSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Order_TPH2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order_TPH2));
        
        string IMigrationMetadata.Id
        {
            get { return "201211111158222_Order_TPH2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
