// <auto-generated />
namespace MvcEasyOrderSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class collectedDateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(collectedDateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201211131150511_collectedDateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
